const ActionType = {

  IS_LOADING: "IS_LOADING",
  LOADING_MSG: "LOADING_MSG",
  USER_TOKEN: "USER_TOKEN",
  DEVICE_TOKEN_REDUCER: "DEVICE_TOKEN_REDUCER",


  //Redux actions
  USER_DATA: "USER_DATA",
  IS_LOGIN: "IS_LOGIN",
  INTERNET_CONNECTED: "INTERNET_CONNECTED",
  INTERNET_DISCONNECTED: "INTERNET_DISCONNECTED",

  //Auth Saga Actions
  DO_LOGIN_SAGA: "DO_LOGIN_SAGA",
  DO_LOGOUT_SAGA: "DO_LOGOUT_SAGA",
  CHANGE_PASSWORD_SAGA: "CHANGE_PASSWORD_SAGA",
  TOKEN_EXPIRED_SAGA: "TOKEN_EXPIRED_SAGA",
  DO_REGISTRATION_SAGA: "DO_REGISTRATION_SAGA",
  GET_COUNTRY_LIST_SAGA: "GET_COUNTRY_LIST_SAGA",
  GET_STATE_LIST_SAGA: "GET_STATE_LIST_SAGA",
  GET_CITY_LIST_SAGA: "GET_CITY_LIST_SAGA",
  UPDATE_PROFILE_SAGA: "UPDATE_PROFILE_SAGA",
  GET_EQUIPMENT_LIST_SAGA: "GET_EQUIPMENT_LIST_SAGA",
  GET_VEHICLE_LIST_SAGA: "GET_VEHICLE_LIST_SAGA",
  GET_COMPANY_VEHICLE_LIST_SAGA: "GET_COMPANY_VEHICLE_LIST_SAGA",
  GET_MODEL_VEHICLE_LIST_SAGA: "GET_MODEL_VEHICLE_LIST_SAGA",
  FORGOT_PASSWORD_SAGA: "FORGOT_PASSWORD_SAGA",
  RESET_PASSWORD_SAGA: "RESET_PASSWORD_SAGA",
  GET_PROFILE_DETAIL: "GET_PROFILE_DETAIL",
  GET_MAKE_LIST: "GET_MAKE_LIST",






}

export default ActionType