export default {
  USER_DATA: "USER_DATA",
  IS_LOGIN: "IS_LOGIN",
  IS_LOGIN_EVENT: "IS_LOGIN_EVENT",
  IS_LOGOUT_EVENT: "IS_LOGOUT_EVENT",
  STOP_LOADER_EVENT: "STOP_LOADER_EVENT",
  ERROR_CODE: 440,
  GET_COUNTRIES_LIST_EVENT:"GET_COUNTRIES_LIST_EVENT",
  GET_STATE_LIST_EVENT:"GET_STATE_LIST_EVENT",
  GET_CITY_LIST_EVENT:"GET_CITY_LIST_EVENT",
  CHANGE_PASSWORD_EVENT:"CHANGE_PASSWORD_EVENT",
  UPDATE_STATUS_BAR_COLOR:"UPDATE_STATUS_BAR_COLOR",
  GET_EQUIPMENT_LIST_CONSTANT:"GET_EQUIPMENT_LIST_CONSTANT",
  GET_VEHICLE_LIST_CONSTANT:"GET_VEHICLE_LIST_CONSTANT",
  GET_MODEL_VEHICLE_LIST_CONSTANT:"GET_MODEL_VEHICLE_LIST_CONSTANT",
  GET_COMPANY_VEHICLE_LIST_CONSTANT:"GET_COMPANY_VEHICLE_LIST_CONSTANT",





};